provider: feishu
project_id: hack-a-mole

feishu:
  app_id: "cli_a93c0992f1399ccd"
  app_secret: "egnFaEXVpX7XSWenOCgOvzZHqsh51tuO"
  bot_name: "fly-pig"
  chat_id: "oc_e113405e179916f79c2f3043ea50d0cf"      # 监听的群ID
  priority: 10           # 优先级（可选）
  keyword: ""       # 关键词（可选）
#  allowed_users:
#    - "ou_user_id_1"
#    - "ou_user_id_2"

session:
  max_history: 50
  timeout_minutes: 30
